python manage.py makemigrations authentification
python manage.py makemigrations end_test_poll
python manage.py makemigrations examinations
python manage.py makemigrations planification
python manage.py makemigrations promotions
python manage.py makemigrations resources
python manage.py makemigrations skills
python manage.py makemigrations stats
python manage.py makemigrations student
python manage.py makemigrations users